version: '3'

services:
  springboot-docker-compose-app-container:
    build: .
    ports:
      - "80:5000"
    depends_on:
    - friendservice
    volumes:
    - .:/code
    networks:
    - mynet
  friendservice:
    build: ./rest-bookstore
    volumes:
    - ./Pirmas:/rest
    ports:
    - 5000:5001
    networks:
    - mynet
    
networks:
    mynet: