version: '3'

services:
  springboot-docker-compose-app-container:
    build: .
    ports:
      - "80:5000"
    depends_on:
    - friendservice
    volumes:
    - .:/code
    networks:
    - mynet
  friendservice:
    build: ./rest-bookstore
    volumes:
    - ./rest-bookstore/rest:/rest
    ports:
    - 80:5000
    networks:
    - mynet
    
networks:
    mynet: