version: '3'

services:
  springboot-docker-compose-app-container:
    build: .
    ports:
      - "5000:5001"
    depends_on:
    - friendservice
    networks:
    - mynet
  friendservice:
    build: ./rest-bookstore
    ports:
    - 80:5000
    networks:
    - mynet
    
networks:
    mynet: